// Conference Companion backend — zero-dependency Node server
// Serves: /r1/ (creation), /setup (phone config page), /api/* (config, schedule extract, site intel scrape)
const http = require('http');
const https = require('https');
const fs = require('fs');
const path = require('path');
const net = require('net');
const dns = require('dns').promises;

const PORT = process.env.PORT || 8787;
const ROOT = __dirname;
const DATA_DIR = path.join(ROOT, 'data');
if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });

// Per-device config store. Device id = pairing key generated by the R1 creation.
function devPath(id) {
  const safe = String(id || 'default').replace(/[^a-zA-Z0-9_-]/g, '').slice(0, 40) || 'default';
  return path.join(DATA_DIR, safe + '.json');
}
function loadConfig(id) {
  try { return JSON.parse(fs.readFileSync(devPath(id), 'utf8')); }
  catch (e) { return { name: '', linkedin: '', landing: '', landingLabel: '', companyUrl: '', companySummary: '', scheduleUrl: '', sessions: [], favs: {}, rev: 0 }; }
}
function saveConfig(id, cfg) {
  // Anti disk-fill: bound both the number of device files and their size.
  const MAX_DEVICES = 2000, MAX_BYTES = 200 * 1024;
  const files = fs.readdirSync(DATA_DIR).filter(f => f.endsWith('.json'));
  if (files.length >= MAX_DEVICES && !fs.existsSync(devPath(id))) {
    throw new Error('device limit reached');
  }
  const s = JSON.stringify(cfg, null, 2);
  if (Buffer.byteLength(s) > MAX_BYTES) throw new Error('config too large');
  fs.writeFileSync(devPath(id), s);
}

// Security note — accepted tradeoff (per Claude review of commit 65d74bb):
// Device id ("cc" + 10 chars, ~31^10) is the ONLY credential and travels in the
// URL + as a pairing QR. CORS is wide open (Access-Control-Allow-Origin: *) so the
// phone/R1 pages can call the API from any origin. The id space is too large to
// brute-force, but a leaked id (browser history, screenshot of the QR, Referer
// header) grants unauthenticated read/write of that user's data from any origin.
// This is intentional for a zero-account companion app; don't add sensitive
// secrets (passwords, tokens) to the stored config.

// ---------- SSRF guard ----------
// Two classic holes this closes at once:
//  (a) Redirect bypass: fetch({redirect:'follow'}) re-validates NOTHING on the
//      hop, so a 302 to http://169.254.169.254/ (cloud metadata) or
//      http://localhost:<port>/api/config slips past a one-time URL check.
//  (b) DNS-rebinding TOCTOU: resolving in the guard then letting fetch() resolve
//      again lets a low-TTL host answer the check with a public IP and the
//      connection with 127.0.0.1. We resolve ONCE and connect to that IP.
// Fix for both: resolve the hostname ourselves, then fetch by connecting to the
// resolved public IP with the original Host header. Redirects are followed
// 'manual'ly and EVERY Location is re-checked (and re-resolved+pinned) with a
// hard hop cap. Only http(s) to public IPs is ever touched.
function isPrivateIp(ip) {
  if (net.isIPv4(ip)) {
    const [a, b] = ip.split('.').map(Number);
    return a === 10 || a === 127 || a === 0 || a === 169 && b === 254 ||
      (a === 172 && b >= 16 && b <= 31) || (a === 192 && b === 168) ||
      (a === 100 && b >= 64 && b <= 127); // CGNAT 100.64/10
  }
  if (net.isIPv6(ip)) {
    const l = ip.toLowerCase().split('%')[0];
    return l === '::1' || l.startsWith('fe80:') || l.startsWith('fc') || l.startsWith('fd') || l === '::';
  }
  return false;
}
// Resolve + validate a URL once; return { ip, host, port, path, proto } pinned to a public IP.
async function pinPublicUrl(url, depth) {
  if (depth > 5) throw new Error('too many redirects');
  let u;
  try { u = new URL(url); } catch (e) { throw new Error('invalid URL'); }
  if (u.protocol !== 'http:' && u.protocol !== 'https:') throw new Error('only http(s) allowed');
  const host = u.hostname;
  let ip;
  if (net.isIP(host)) {
    ip = host;
    if (isPrivateIp(ip)) throw new Error('private address blocked');
  } else {
    const addrs = await dns.lookup(host, { all: true });
    const pub = addrs.map(a => a.address).filter(a => !isPrivateIp(a));
    if (!pub.length) throw new Error('host resolves only to private/blocked addresses');
    ip = pub[0]; // pin to one public resolution for the whole connection
  }
  return { ip, host, port: u.port || (u.protocol === 'https:' ? 443 : 80), path: u.pathname + u.search, proto: u.protocol };
}
// Issue the actual request against the pinned IP (never the hostname), so DNS
// cannot change between validation and connection. `Host`/SNI still use the
// real hostname so virtual-hosted sites and TLS cert checks work correctly.
const MAX_RESPONSE_BYTES = 5 * 1024 * 1024;
function fetchPinned(pinned, timeoutMs) {
  return new Promise((resolve, reject) => {
    const lib = pinned.proto === 'https:' ? https : http;
    const opts = {
      host: pinned.ip,
      port: pinned.port,
      path: pinned.path,
      method: 'GET',
      timeout: timeoutMs,
      headers: {
        'Host': pinned.host,
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) ConfCompanion/1.0',
        'Accept': 'text/html,application/xhtml+xml'
      }
    };
    if (lib === https) opts.servername = pinned.host; // SNI + cert hostname check against the real name
    const req = lib.request(opts, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400) {
        res.resume();
        return resolve({ redirectTo: res.headers.location });
      }
      if (res.statusCode < 200 || res.statusCode >= 300) {
        res.resume();
        return reject(new Error('HTTP ' + res.statusCode));
      }
      const chunks = [];
      let size = 0;
      res.on('data', (c) => {
        size += c.length;
        if (size > MAX_RESPONSE_BYTES) { req.destroy(new Error('response too large')); return; }
        chunks.push(c);
      });
      res.on('end', () => resolve({ text: Buffer.concat(chunks).toString('utf8') }));
    });
    req.on('timeout', () => req.destroy(new Error('timeout')));
    req.on('error', reject);
    req.end();
  });
}
// Fetch HTML via IP-pinned connection, manually following + re-validating redirects.
async function fetchHtml(url, timeoutMs = 12000, depth = 0) {
  const pinned = await pinPublicUrl(url, depth);
  const r = await fetchPinned(pinned, timeoutMs);
  if (r.redirectTo !== undefined) {
    if (!r.redirectTo) throw new Error('redirect with no Location');
    // Re-validate + re-resolve + re-pin the next hop (absolute or relative) before following.
    const next = r.redirectTo.startsWith('http') ? r.redirectTo
      : (pinned.proto + '//' + pinned.host + (r.redirectTo.startsWith('/') ? r.redirectTo : '/' + r.redirectTo));
    return fetchHtml(next, timeoutMs, depth + 1);
  }
  return r.text;
}

function htmlToText(html) {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<noscript[\s\S]*?<\/noscript>/gi, ' ')
    .replace(/<!--[\s\S]*?-->/g, ' ')
    .replace(/<(br|\/p|\/div|\/li|\/tr|\/h[1-6]|\/section|\/article|\/header)[^>]*>/gi, '\n')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&#(\d+);/g, (m, d) => String.fromCharCode(+d))
    .replace(/[ \t]+/g, ' ')
    .replace(/\n\s*\n+/g, '\n')
    .trim();
}

// ---------- Schedule parsing (heuristic) ----------
// Strategy 0: structured JSON embedded in the page. Many conference sites (WBR/eTail,
// anything Vue/React server-seeded, or schema.org ld+json) ship the full agenda inline.
function decodeEntities(s) {
  return s.replace(/&quot;/g, '"').replace(/&#0?39;/g, "'").replace(/&lt;/g, '<')
          .replace(/&gt;/g, '>').replace(/&#(\d+);/g, (m, d) => String.fromCharCode(+d))
          .replace(/&amp;/g, '&');
}
function stripTags(s) { return String(s || '').replace(/<[^>]+>/g, '').trim(); }
function speakerLine(sp) {
  if (!Array.isArray(sp)) return '';
  return sp.map(x => [x.name, x.job_title, x.company].filter(Boolean).join(', ')).join(' · ').slice(0, 160);
}
function parseStructured(html) {
  // 0a: WBR/Vue ":days" prop — HTML-escaped JSON array of {name, groups[{tracks[{sessions[...]}]}]}
  let m = html.match(/:days\s*=\s*"(\[[\s\S]*?)"\s*[:>a-z-]/i);
  if (m) {
    try {
      const days = JSON.parse(decodeEntities(m[1]));
      const out = [];
      for (const d of days) {
        const dayShort = stripTags(d.date_shortest || d.name || '');
        for (const g of d.groups || []) for (const t of g.tracks || []) for (const s of t.sessions || []) {
          const time = (dayShort ? dayShort + ' ' : '') + (s.start || '') + (s.end ? '–' + s.end : '');
          out.push({
            id: out.length,
            time: time.trim().slice(0, 40),
            title: stripTags(s.name).slice(0, 120),
            speaker: speakerLine(s.speakers),
            desc: stripTags(s.description).slice(0, 500),
            day: stripTags(d.name || '')
          });
        }
      }
      if (out.length) return out;
    } catch (e) { /* fall through */ }
  }
  // 0b: schema.org ld+json Event/EventSchedule blocks
  const ld = [...html.matchAll(/<script[^>]*application\/ld\+json[^>]*>([\s\S]*?)<\/script>/gi)];
  for (const b of ld) {
    try {
      let j = JSON.parse(b[1].trim());
      const items = Array.isArray(j) ? j : (j['@graph'] || [j]);
      const evs = items.filter(x => /Event/i.test(String(x['@type'])) && x.name && x.startDate);
      if (evs.length >= 3) {
        return evs.slice(0, 200).map((e, i) => ({
          id: i,
          time: String(e.startDate).replace('T', ' ').slice(0, 16),
          title: stripTags(e.name).slice(0, 120),
          speaker: stripTags((e.performer && (e.performer.name || (e.performer[0] || {}).name)) || '').slice(0, 80),
          desc: stripTags(e.description || '').slice(0, 500)
        }));
      }
    } catch (e) { /* fall through */ }
  }
  return null;
}

// Looks for lines with time patterns; the following title-ish text becomes the session.
const TIME_RE = /\b(\d{1,2}:\d{2}\s*(?:AM|PM|am|pm)?(?:\s*[-–—to]+\s*\d{1,2}:\d{2}\s*(?:AM|PM|am|pm)?)?)\b/;
function parseSchedule(text) {
  const lines = text.split('\n').map(l => l.trim()).filter(l => l.length > 0);
  const sessions = [];
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(TIME_RE);
    if (!m) continue;
    const time = m[1].replace(/\s+/g, '');
    // title: rest of this line after the time, else the next non-time line
    let title = lines[i].replace(TIME_RE, '').replace(/^[\s\-–—:|•]+|[\s\-–—:|•]+$/g, '');
    let speaker = '';
    let j = i + 1;
    if (title.length < 4 && j < lines.length && !TIME_RE.test(lines[j])) { title = lines[j]; j++; }
    // speaker: next short line that looks like a name/company (has letters, < 80 chars, not a time)
    if (j < lines.length && !TIME_RE.test(lines[j]) && lines[j].length < 80 && /[A-Za-z]/.test(lines[j])) speaker = lines[j];
    title = title.slice(0, 120);
    if (title.length >= 4) sessions.push({ id: sessions.length, time, title, speaker: speaker.slice(0, 80) });
    if (sessions.length >= 60) break;
  }
  return sessions;
}

// ---------- HTTP plumbing ----------
function send(res, code, body, type) {
  const buf = typeof body === 'string' || Buffer.isBuffer(body) ? body : JSON.stringify(body);
  res.writeHead(code, {
    'Content-Type': type || 'application/json; charset=utf-8',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Cache-Control': 'no-store'
  });
  res.end(buf);
}
function readBody(req) {
  return new Promise((resolve, reject) => {
    let d = '';
    req.on('data', c => { d += c; if (d.length > 1e6) { req.destroy(); reject(new Error('body too large')); } });
    req.on('end', () => { try { resolve(d ? JSON.parse(d) : {}); } catch (e) { reject(e); } });
    req.on('error', reject);
  });
}
const MIME = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript', '.css': 'text/css', '.png': 'image/png', '.json': 'application/json' };

const server = http.createServer(async (req, res) => {
  const u = new URL(req.url, 'http://x');
  const p = u.pathname;
  if (req.method === 'OPTIONS') return send(res, 204, '');
  try {
    // ---- API ---- (device id via ?d= query or body.d)
    const qd = u.searchParams.get('d');
    if (p === '/healthz') return send(res, 200, { ok: true, up: process.uptime() | 0 });
    if (p === '/api/config' && req.method === 'GET') return send(res, 200, loadConfig(qd));
    if (p === '/api/config' && req.method === 'POST') {
      const body = await readBody(req);
      const id = body.d || qd;
      delete body.d;
      const prev = loadConfig(id);
      // Merge favorites from phone + R1 rather than overwriting (cross-device favs).
      if (body.favs && prev.favs) body.favs = Object.assign({}, prev.favs, body.favs);
      const cfg = { ...prev, ...body };
      cfg.rev = (cfg.rev || 0) + 1;
      saveConfig(id, cfg);
      return send(res, 200, { ok: true, rev: cfg.rev });
    }
    if (p === '/api/schedule' && req.method === 'POST') {
      const { url, d } = await readBody(req);
      const id = d || qd;
      if (!url) return send(res, 400, { error: 'url required' });
      const html = await fetchHtml(url);
      const structured = parseStructured(html);
      const sessions = structured || parseSchedule(htmlToText(html));
      const cfg = loadConfig(id);
      cfg.scheduleUrl = url;
      if (sessions.length) cfg.sessions = sessions;
      cfg.rev = (cfg.rev || 0) + 1;
      saveConfig(id, cfg);
      return send(res, 200, { sessions, source: structured ? 'structured' : 'heuristic', rawText: sessions.length ? undefined : htmlToText(html).slice(0, 6000) });
    }
    if (p === '/api/extract' && req.method === 'POST') {
      const { url, save, d } = await readBody(req);
      const id = d || qd;
      if (!url) return send(res, 400, { error: 'url required' });
      const text = htmlToText(await fetchHtml(url)).slice(0, 5000);
      if (save === 'company') {
        const cfg = loadConfig(id);
        cfg.companyUrl = url;
        cfg.companySummary = text.slice(0, 2500);
        saveConfig(id, cfg);
      }
      return send(res, 200, { text });
    }
    // Prospect intel context: bundle my-company summary + prospect scrape for the R1 LLM
    if (p === '/api/intel' && req.method === 'POST') {
      const { prospect, prospectUrl, d } = await readBody(req);
      const cfg = loadConfig(d || qd);
      let prospectText = '';
      if (prospectUrl) { try { prospectText = htmlToText(await fetchHtml(prospectUrl)).slice(0, 2500); } catch (e) { prospectText = ''; } }
      return send(res, 200, {
        myCompany: cfg.companySummary || '',
        prospect: prospect || '',
        prospectText
      });
    }
    // ---- Static ----
    if (p === '/manifest.json') {
      return send(res, 200, JSON.stringify({
        name: 'Conf Companion', short_name: 'ConfComp',
        start_url: '/phone' + (qd ? '?d=' + qd : ''),
        display: 'standalone', background_color: '#111111', theme_color: '#ff6600',
        icons: [{ src: '/icon-192.png', sizes: '192x192', type: 'image/png' }]
      }), 'application/manifest+json');
    }
    let fp = null;
    if (p === '/' || p === '/phone' || p === '/phone/') fp = path.join(ROOT, 'phone.html');
    else if (p === '/setup') fp = path.join(ROOT, 'setup.html');
    else if (p === '/icon-192.png') fp = path.join(ROOT, 'icon-192.png');
    else if (p === '/r1' || p === '/r1/') fp = path.join(ROOT, 'r1', 'index.html');
    else if (p.startsWith('/r1/')) fp = path.join(ROOT, 'r1', p.slice(4).replace(/\.\./g, ''));
    if (fp && fs.existsSync(fp)) return send(res, 200, fs.readFileSync(fp), MIME[path.extname(fp)] || 'application/octet-stream');
    return send(res, 404, { error: 'not found' });
  } catch (e) {
    return send(res, 500, { error: String(e.message || e) });
  }
});
server.listen(PORT, () => console.log('ConfCompanion on http://localhost:' + PORT));
