// Conference Companion backend — zero-dependency Node server
// Serves: /r1/ (creation), /setup (phone config page), /api/* (config, schedule extract, site intel scrape)
const http = require('http');
const fs = require('fs');
const path = require('path');
const net = require('net');
const dns = require('dns').promises;

const PORT = process.env.PORT || 8787;
const ROOT = __dirname;
const DATA_DIR = path.join(ROOT, 'data');
if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });

// Per-device config store. Device id = pairing key generated by the R1 creation.
function devPath(id) {
  const safe = String(id || 'default').replace(/[^a-zA-Z0-9_-]/g, '').slice(0, 40) || 'default';
  return path.join(DATA_DIR, safe + '.json');
}
function loadConfig(id) {
  try { return JSON.parse(fs.readFileSync(devPath(id), 'utf8')); }
  catch (e) { return { name: '', linkedin: '', landing: '', landingLabel: '', companyUrl: '', companySummary: '', scheduleUrl: '', sessions: [], rev: 0 }; }
}
function saveConfig(id, cfg) { fs.writeFileSync(devPath(id), JSON.stringify(cfg, null, 2)); }

// ---------- SSRF guard: only allow http(s) to public hosts ----------
// Blocks file:, localhost, link-local (169.254.169.254), loopback, and private ranges.
function isPrivateIp(ip) {
  if (net.isIPv4(ip)) {
    const [a, b] = ip.split('.').map(Number);
    return a === 10 || a === 127 || a === 0 || a === 169 && b === 254 ||
      (a === 172 && b >= 16 && b <= 31) || (a === 192 && b === 168) ||
      (a === 100 && b >= 64 && b <= 127); // CGNAT 100.64/10
  }
  if (net.isIPv6(ip)) {
    const l = ip.toLowerCase().split('%')[0];
    return l === '::1' || l.startsWith('fe80:') || l.startsWith('fc') || l.startsWith('fd') || l === '::';
  }
  return false;
}
async function assertPublicUrl(url) {
  let u;
  try { u = new URL(url); } catch (e) { throw new Error('invalid URL'); }
  if (u.protocol !== 'http:' && u.protocol !== 'https:') throw new Error('only http(s) allowed');
  const host = u.hostname;
  // direct IP literal
  if (net.isIP(host)) { if (isPrivateIp(host)) throw new Error('private address blocked'); return; }
  // resolve hostname (incl. IPv6) and reject if any resolution is private
  let addrs;
  try { addrs = await dns.lookup(host, { all: true }); }
  catch (e) { throw new Error('DNS resolution failed'); }
  for (const a of addrs) if (isPrivateIp(a.address)) throw new Error('private address blocked');
}

// ---------- HTML fetching + cleaning ----------
async function fetchHtml(url, timeoutMs = 12000) {
  await assertPublicUrl(url);
  const ctl = new AbortController();
  const t = setTimeout(() => ctl.abort(), timeoutMs);
  try {
    const r = await fetch(url, {
      signal: ctl.signal,
      redirect: 'follow',
      headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) ConfCompanion/1.0', 'Accept': 'text/html,application/xhtml+xml' }
    });
    if (!r.ok) throw new Error('HTTP ' + r.status);
    return await r.text();
  } finally { clearTimeout(t); }
}

function htmlToText(html) {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<noscript[\s\S]*?<\/noscript>/gi, ' ')
    .replace(/<!--[\s\S]*?-->/g, ' ')
    .replace(/<(br|\/p|\/div|\/li|\/tr|\/h[1-6]|\/section|\/article|\/header)[^>]*>/gi, '\n')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&#(\d+);/g, (m, d) => String.fromCharCode(+d))
    .replace(/[ \t]+/g, ' ')
    .replace(/\n\s*\n+/g, '\n')
    .trim();
}

// ---------- Schedule parsing (heuristic) ----------
// Strategy 0: structured JSON embedded in the page. Many conference sites (WBR/eTail,
// anything Vue/React server-seeded, or schema.org ld+json) ship the full agenda inline.
function decodeEntities(s) {
  return s.replace(/&quot;/g, '"').replace(/&#0?39;/g, "'").replace(/&lt;/g, '<')
          .replace(/&gt;/g, '>').replace(/&#(\d+);/g, (m, d) => String.fromCharCode(+d))
          .replace(/&amp;/g, '&');
}
function stripTags(s) { return String(s || '').replace(/<[^>]+>/g, '').trim(); }
function speakerLine(sp) {
  if (!Array.isArray(sp)) return '';
  return sp.map(x => [x.name, x.job_title, x.company].filter(Boolean).join(', ')).join(' · ').slice(0, 160);
}
function parseStructured(html) {
  // 0a: WBR/Vue ":days" prop — HTML-escaped JSON array of {name, groups[{tracks[{sessions[...]}]}]}
  let m = html.match(/:days\s*=\s*"(\[[\s\S]*?)"\s*[:>a-z-]/i);
  if (m) {
    try {
      const days = JSON.parse(decodeEntities(m[1]));
      const out = [];
      for (const d of days) {
        const dayShort = stripTags(d.date_shortest || d.name || '');
        for (const g of d.groups || []) for (const t of g.tracks || []) for (const s of t.sessions || []) {
          const time = (dayShort ? dayShort + ' ' : '') + (s.start || '') + (s.end ? '–' + s.end : '');
          out.push({
            id: out.length,
            time: time.trim().slice(0, 40),
            title: stripTags(s.name).slice(0, 120),
            speaker: speakerLine(s.speakers),
            desc: stripTags(s.description).slice(0, 500),
            day: stripTags(d.name || '')
          });
        }
      }
      if (out.length) return out;
    } catch (e) { /* fall through */ }
  }
  // 0b: schema.org ld+json Event/EventSchedule blocks
  const ld = [...html.matchAll(/<script[^>]*application\/ld\+json[^>]*>([\s\S]*?)<\/script>/gi)];
  for (const b of ld) {
    try {
      let j = JSON.parse(b[1].trim());
      const items = Array.isArray(j) ? j : (j['@graph'] || [j]);
      const evs = items.filter(x => /Event/i.test(String(x['@type'])) && x.name && x.startDate);
      if (evs.length >= 3) {
        return evs.slice(0, 200).map((e, i) => ({
          id: i,
          time: String(e.startDate).replace('T', ' ').slice(0, 16),
          title: stripTags(e.name).slice(0, 120),
          speaker: stripTags((e.performer && (e.performer.name || (e.performer[0] || {}).name)) || '').slice(0, 80),
          desc: stripTags(e.description || '').slice(0, 500)
        }));
      }
    } catch (e) { /* fall through */ }
  }
  return null;
}

// Looks for lines with time patterns; the following title-ish text becomes the session.
const TIME_RE = /\b(\d{1,2}:\d{2}\s*(?:AM|PM|am|pm)?(?:\s*[-–—to]+\s*\d{1,2}:\d{2}\s*(?:AM|PM|am|pm)?)?)\b/;
function parseSchedule(text) {
  const lines = text.split('\n').map(l => l.trim()).filter(l => l.length > 0);
  const sessions = [];
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(TIME_RE);
    if (!m) continue;
    const time = m[1].replace(/\s+/g, '');
    // title: rest of this line after the time, else the next non-time line
    let title = lines[i].replace(TIME_RE, '').replace(/^[\s\-–—:|•]+|[\s\-–—:|•]+$/g, '');
    let speaker = '';
    let j = i + 1;
    if (title.length < 4 && j < lines.length && !TIME_RE.test(lines[j])) { title = lines[j]; j++; }
    // speaker: next short line that looks like a name/company (has letters, < 80 chars, not a time)
    if (j < lines.length && !TIME_RE.test(lines[j]) && lines[j].length < 80 && /[A-Za-z]/.test(lines[j])) speaker = lines[j];
    title = title.slice(0, 120);
    if (title.length >= 4) sessions.push({ id: sessions.length, time, title, speaker: speaker.slice(0, 80) });
    if (sessions.length >= 60) break;
  }
  return sessions;
}

// ---------- HTTP plumbing ----------
function send(res, code, body, type) {
  const buf = typeof body === 'string' || Buffer.isBuffer(body) ? body : JSON.stringify(body);
  res.writeHead(code, {
    'Content-Type': type || 'application/json; charset=utf-8',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Cache-Control': 'no-store'
  });
  res.end(buf);
}
function readBody(req) {
  return new Promise((resolve, reject) => {
    let d = '';
    req.on('data', c => { d += c; if (d.length > 1e6) req.destroy(); });
    req.on('end', () => { try { resolve(d ? JSON.parse(d) : {}); } catch (e) { reject(e); } });
    req.on('error', reject);
  });
}
const MIME = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript', '.css': 'text/css', '.png': 'image/png', '.json': 'application/json' };

const server = http.createServer(async (req, res) => {
  const u = new URL(req.url, 'http://x');
  const p = u.pathname;
  if (req.method === 'OPTIONS') return send(res, 204, '');
  try {
    // ---- API ---- (device id via ?d= query or body.d)
    const qd = u.searchParams.get('d');
    if (p === '/healthz') return send(res, 200, { ok: true, up: process.uptime() | 0 });
    if (p === '/api/config' && req.method === 'GET') return send(res, 200, loadConfig(qd));
    if (p === '/api/config' && req.method === 'POST') {
      const body = await readBody(req);
      const id = body.d || qd;
      delete body.d;
      const cfg = { ...loadConfig(id), ...body };
      cfg.rev = (cfg.rev || 0) + 1;
      saveConfig(id, cfg);
      return send(res, 200, { ok: true, rev: cfg.rev });
    }
    if (p === '/api/schedule' && req.method === 'POST') {
      const { url, d } = await readBody(req);
      const id = d || qd;
      if (!url) return send(res, 400, { error: 'url required' });
      const html = await fetchHtml(url);
      const structured = parseStructured(html);
      const sessions = structured || parseSchedule(htmlToText(html));
      const cfg = loadConfig(id);
      cfg.scheduleUrl = url;
      if (sessions.length) cfg.sessions = sessions;
      cfg.rev = (cfg.rev || 0) + 1;
      saveConfig(id, cfg);
      return send(res, 200, { sessions, source: structured ? 'structured' : 'heuristic', rawText: sessions.length ? undefined : htmlToText(html).slice(0, 6000) });
    }
    if (p === '/api/extract' && req.method === 'POST') {
      const { url, save, d } = await readBody(req);
      const id = d || qd;
      if (!url) return send(res, 400, { error: 'url required' });
      const text = htmlToText(await fetchHtml(url)).slice(0, 5000);
      if (save === 'company') {
        const cfg = loadConfig(id);
        cfg.companyUrl = url;
        cfg.companySummary = text.slice(0, 2500);
        saveConfig(id, cfg);
      }
      return send(res, 200, { text });
    }
    // Prospect intel context: bundle my-company summary + prospect scrape for the R1 LLM
    if (p === '/api/intel' && req.method === 'POST') {
      const { prospect, prospectUrl, d } = await readBody(req);
      const cfg = loadConfig(d || qd);
      let prospectText = '';
      if (prospectUrl) { try { prospectText = htmlToText(await fetchHtml(prospectUrl)).slice(0, 2500); } catch (e) { prospectText = ''; } }
      return send(res, 200, {
        myCompany: cfg.companySummary || '',
        prospect: prospect || '',
        prospectText
      });
    }
    // ---- Static ----
    if (p === '/manifest.json') {
      return send(res, 200, JSON.stringify({
        name: 'Conf Companion', short_name: 'ConfComp',
        start_url: '/setup' + (qd ? '?d=' + qd : ''),
        display: 'standalone', background_color: '#111111', theme_color: '#ff6600',
        icons: [{ src: '/icon-192.png', sizes: '192x192', type: 'image/png' }]
      }), 'application/manifest+json');
    }
    let fp = null;
    if (p === '/' || p === '/setup') fp = path.join(ROOT, 'setup.html');
    else if (p === '/icon-192.png') fp = path.join(ROOT, 'icon-192.png');
    else if (p === '/r1' || p === '/r1/') fp = path.join(ROOT, 'r1', 'index.html');
    else if (p.startsWith('/r1/')) fp = path.join(ROOT, 'r1', p.slice(4).replace(/\.\./g, ''));
    if (fp && fs.existsSync(fp)) return send(res, 200, fs.readFileSync(fp), MIME[path.extname(fp)] || 'application/octet-stream');
    return send(res, 404, { error: 'not found' });
  } catch (e) {
    return send(res, 500, { error: String(e.message || e) });
  }
});
server.listen(PORT, () => console.log('ConfCompanion on http://localhost:' + PORT));
