// Conference Companion backend — zero-dependency Node server
// Serves: /r1/ (creation), /setup (phone config page), /api/* (config, schedule extract, site intel scrape)
const http = require('http');
const https = require('https');
const zlib = require('zlib');
const fs = require('fs');
const path = require('path');
const net = require('net');
const dns = require('dns').promises;

const PORT = process.env.PORT || 8787;
const ROOT = __dirname;
const DATA_DIR = path.join(ROOT, 'data');
if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });

// Per-device config store. Device id = pairing key generated by the R1 creation.
function devPath(id) {
  const safe = String(id || 'default').replace(/[^a-zA-Z0-9_-]/g, '').slice(0, 40) || 'default';
  return path.join(DATA_DIR, safe + '.json');
}
function loadConfig(id) {
  try { return JSON.parse(fs.readFileSync(devPath(id), 'utf8')); }
  catch (e) { return { name: '', linkedin: '', landing: '', landingLabel: '', companyUrl: '', companySummary: '', scheduleUrl: '', sessions: [], favs: {}, intel: {}, pitchPoints: [], brandName: '', brandColor: '#5e6ad2', rev: 0 }; }
}
function saveConfig(id, cfg) {
  // Anti disk-fill: bound both the number of device files and their size.
  const MAX_DEVICES = 2000, MAX_BYTES = 200 * 1024;
  const files = fs.readdirSync(DATA_DIR).filter(f => f.endsWith('.json'));
  if (files.length >= MAX_DEVICES && !fs.existsSync(devPath(id))) {
    throw new Error('device limit reached');
  }
  const s = JSON.stringify(cfg, null, 2);
  if (Buffer.byteLength(s) > MAX_BYTES) throw new Error('config too large');
  fs.writeFileSync(devPath(id), s);
}

// Security note — accepted tradeoff (per Claude review of commit 65d74bb):
// Device id ("cc" + 10 chars, ~31^10) is the ONLY credential and travels in the
// URL + as a pairing QR. CORS is wide open (Access-Control-Allow-Origin: *) so the
// phone/R1 pages can call the API from any origin. The id space is too large to
// brute-force, but a leaked id (browser history, screenshot of the QR, Referer
// header) grants unauthenticated read/write of that user's data from any origin.
// This is intentional for a zero-account companion app; don't add sensitive
// secrets (passwords, tokens) to the stored config.

// ---------- SSRF guard ----------
// Two classic holes this closes at once:
//  (a) Redirect bypass: fetch({redirect:'follow'}) re-validates NOTHING on the
//      hop, so a 302 to http://169.254.169.254/ (cloud metadata) or
//      http://localhost:<port>/api/config slips past a one-time URL check.
//  (b) DNS-rebinding TOCTOU: resolving in the guard then letting fetch() resolve
//      again lets a low-TTL host answer the check with a public IP and the
//      connection with 127.0.0.1. We resolve ONCE and connect to that IP.
// Fix for both: resolve the hostname ourselves, then fetch by connecting to the
// resolved public IP with the original Host header. Redirects are followed
// 'manual'ly and EVERY Location is re-checked (and re-resolved+pinned) with a
// hard hop cap. Only http(s) to public IPs is ever touched.
function isPrivateIp(ip) {
  if (net.isIPv4(ip)) {
    const [a, b] = ip.split('.').map(Number);
    return a === 10 || a === 127 || a === 0 || a === 169 && b === 254 ||
      (a === 172 && b >= 16 && b <= 31) || (a === 192 && b === 168) ||
      (a === 100 && b >= 64 && b <= 127); // CGNAT 100.64/10
  }
  if (net.isIPv6(ip)) {
    const l = ip.toLowerCase().split('%')[0];
    return l === '::1' || l.startsWith('fe80:') || l.startsWith('fc') || l.startsWith('fd') || l === '::';
  }
  return false;
}
// Resolve + validate a URL once; return { ip, host, port, path, proto } pinned to a public IP.
async function pinPublicUrl(url, depth) {
  if (depth > 5) throw new Error('too many redirects');
  let u;
  try { u = new URL(url); } catch (e) { throw new Error('invalid URL'); }
  if (u.protocol !== 'http:' && u.protocol !== 'https:') throw new Error('only http(s) allowed');
  const host = u.hostname;
  let ip;
  if (net.isIP(host)) {
    ip = host;
    if (isPrivateIp(ip)) throw new Error('private address blocked');
  } else {
    const addrs = await dns.lookup(host, { all: true });
    const pub = addrs.map(a => a.address).filter(a => !isPrivateIp(a));
    if (!pub.length) throw new Error('host resolves only to private/blocked addresses');
    ip = pub[0]; // pin to one public resolution for the whole connection
  }
  return { ip, host, port: u.port || (u.protocol === 'https:' ? 443 : 80), path: u.pathname + u.search, proto: u.protocol };
}
// Issue the actual request against the pinned IP (never the hostname), so DNS
// cannot change between validation and connection. `Host`/SNI still use the
// real hostname so virtual-hosted sites and TLS cert checks work correctly.
const MAX_RESPONSE_BYTES = 5 * 1024 * 1024;
function fetchPinnedRaw(pinned, timeoutMs) {
  return new Promise((resolve, reject) => {
    const lib = pinned.proto === 'https:' ? https : http;
    const opts = {
      host: pinned.ip,
      port: pinned.port,
      path: pinned.path,
      method: 'GET',
      timeout: timeoutMs,
      headers: {
        'Host': pinned.host,
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) ConfCompanion/1.0',
        'Accept': '*/*'
      }
    };
    if (lib === https) opts.servername = pinned.host; // SNI + cert hostname check against the real name
    const req = lib.request(opts, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400) {
        res.resume();
        return resolve({ redirectTo: res.headers.location });
      }
      if (res.statusCode < 200 || res.statusCode >= 300) {
        res.resume();
        return reject(new Error('HTTP ' + res.statusCode));
      }
      const chunks = [];
      let size = 0;
      res.on('data', (c) => {
        size += c.length;
        if (size > MAX_RESPONSE_BYTES) { req.destroy(new Error('response too large')); return; }
        chunks.push(c);
      });
      res.on('end', () => resolve({ buffer: Buffer.concat(chunks), contentType: res.headers['content-type'] || '' }));
    });
    req.on('timeout', () => req.destroy(new Error('timeout')));
    req.on('error', reject);
    req.end();
  });
}
// Fetch raw bytes via IP-pinned connection, manually following + re-validating redirects.
async function fetchBytes(url, timeoutMs = 12000, depth = 0) {
  const pinned = await pinPublicUrl(url, depth);
  const r = await fetchPinnedRaw(pinned, timeoutMs);
  if (r.redirectTo !== undefined) {
    if (!r.redirectTo) throw new Error('redirect with no Location');
    // Re-validate + re-resolve + re-pin the next hop (absolute or relative) before following.
    const next = r.redirectTo.startsWith('http') ? r.redirectTo
      : (pinned.proto + '//' + pinned.host + (r.redirectTo.startsWith('/') ? r.redirectTo : '/' + r.redirectTo));
    return fetchBytes(next, timeoutMs, depth + 1);
  }
  return r;
}
async function fetchHtml(url, timeoutMs = 12000) {
  const { buffer } = await fetchBytes(url, timeoutMs);
  return buffer.toString('utf8');
}

// ---------- Favicon discovery + decoding ("pixel math" brand-color extraction) ----------
// No image-processing dependency: PNG uses zlib (Node core) for its DEFLATE stream, so a
// minimal PNG decoder is ~40 lines of vanilla JS. ICO wraps either a PNG or an uncompressed
// BMP; both are handled. GIF/JPEG/SVG favicons are not decoded — swatches just come back
// empty and the caller falls back to manual color entry.
function resolveUrl(base, href) { try { return new URL(href, base).toString(); } catch (e) { return null; } }
function findFaviconHref(html) {
  const re = /<link\s+[^>]*rel=["']([^"']*icon[^"']*)["'][^>]*>/gi;
  let m, best = null;
  while ((m = re.exec(html))) {
    const hrefM = m[0].match(/href=["']([^"']+)["']/i);
    if (!hrefM) continue;
    if (/apple-touch-icon/i.test(m[1])) return hrefM[1]; // usually the highest-fidelity PNG
    if (!best) best = hrefM[1];
  }
  return best;
}
async function getFaviconUrl(siteUrl) {
  let html = '';
  try { html = await fetchHtml(siteUrl, 8000); } catch (e) { /* fall through to /favicon.ico guess */ }
  const href = html && findFaviconHref(html);
  return (href && resolveUrl(siteUrl, href)) || resolveUrl(siteUrl, '/favicon.ico');
}
function decodePNG(buf) {
  if (buf.length < 8 || buf.readUInt32BE(0) !== 0x89504e47) throw new Error('not a PNG');
  let offset = 8, width, height, bitDepth, colorType, interlace, palette = null, trns = null;
  const idat = [];
  while (offset + 8 <= buf.length) {
    const len = buf.readUInt32BE(offset);
    const type = buf.toString('ascii', offset + 4, offset + 8);
    const data = buf.slice(offset + 8, offset + 8 + len);
    if (type === 'IHDR') {
      width = data.readUInt32BE(0); height = data.readUInt32BE(4);
      bitDepth = data[8]; colorType = data[9]; interlace = data[12];
    } else if (type === 'PLTE') palette = data;
    else if (type === 'tRNS') trns = data;
    else if (type === 'IDAT') idat.push(data);
    else if (type === 'IEND') break;
    offset += 8 + len + 4;
  }
  if (bitDepth !== 8) throw new Error('unsupported PNG bit depth');
  if (interlace) throw new Error('interlaced PNG unsupported');
  const channels = { 0: 1, 2: 3, 3: 1, 4: 2, 6: 4 }[colorType];
  if (!channels) throw new Error('unsupported PNG color type');
  const raw = zlib.inflateSync(Buffer.concat(idat));
  const stride = width * channels;
  const pixels = Buffer.alloc(height * stride);
  let pos = 0;
  for (let y = 0; y < height; y++) {
    const filter = raw[pos]; pos++;
    const rowStart = y * stride;
    for (let x = 0; x < stride; x++) {
      const raw8 = raw[pos + x];
      const a = x >= channels ? pixels[rowStart + x - channels] : 0;
      const b = y > 0 ? pixels[rowStart - stride + x] : 0;
      const c = (x >= channels && y > 0) ? pixels[rowStart - stride + x - channels] : 0;
      let val;
      switch (filter) {
        case 0: val = raw8; break;
        case 1: val = raw8 + a; break;
        case 2: val = raw8 + b; break;
        case 3: val = raw8 + ((a + b) >> 1); break;
        case 4: {
          const p = a + b - c, pa = Math.abs(p - a), pb = Math.abs(p - b), pc = Math.abs(p - c);
          val = raw8 + (pa <= pb && pa <= pc ? a : (pb <= pc ? b : c)); break;
        }
        default: throw new Error('bad PNG filter');
      }
      pixels[rowStart + x] = val & 0xff;
    }
    pos += stride;
  }
  const out = Buffer.alloc(width * height * 4);
  for (let i = 0, p = 0; i < width * height; i++, p += channels) {
    let r, g, b, a = 255;
    if (colorType === 2) { r = pixels[p]; g = pixels[p + 1]; b = pixels[p + 2]; }
    else if (colorType === 6) { r = pixels[p]; g = pixels[p + 1]; b = pixels[p + 2]; a = pixels[p + 3]; }
    else if (colorType === 0) { r = g = b = pixels[p]; }
    else if (colorType === 4) { r = g = b = pixels[p]; a = pixels[p + 1]; }
    else { // colorType 3: palette
      const idx = pixels[p];
      r = palette[idx * 3]; g = palette[idx * 3 + 1]; b = palette[idx * 3 + 2];
      a = trns && trns[idx] !== undefined ? trns[idx] : 255;
    }
    out[i * 4] = r; out[i * 4 + 1] = g; out[i * 4 + 2] = b; out[i * 4 + 3] = a;
  }
  return { width, height, pixels: out };
}
// Uncompressed 24/32bpp BMP as embedded in an ICO (no BITMAPFILEHEADER; height is doubled
// to account for the legacy AND-mask row that trails the color data).
function decodeIcoBitmap(buf) {
  const headerSize = buf.readUInt32LE(0);
  const width = buf.readInt32LE(4);
  const height = Math.abs(buf.readInt32LE(8)) / 2;
  const bitCount = buf.readUInt16LE(14);
  const compression = buf.readUInt32LE(16);
  if (compression !== 0) throw new Error('compressed ICO bitmap unsupported');
  if (bitCount !== 24 && bitCount !== 32) throw new Error('unsupported ICO bit depth');
  const bpp = bitCount / 8;
  const rowSize = Math.floor((bitCount * width + 31) / 32) * 4;
  const out = Buffer.alloc(width * height * 4);
  for (let y = 0; y < height; y++) {
    const srcRow = headerSize + (height - 1 - y) * rowSize; // BMP rows are bottom-up
    for (let x = 0; x < width; x++) {
      const p = srcRow + x * bpp;
      const o = (y * width + x) * 4;
      out[o] = buf[p + 2]; out[o + 1] = buf[p + 1]; out[o + 2] = buf[p]; out[o + 3] = bpp === 4 ? buf[p + 3] : 255;
    }
  }
  return { width, height, pixels: out };
}
function decodeIco(buf) {
  const count = buf.readUInt16LE(4);
  let best = null;
  for (let i = 0; i < count; i++) {
    const off = 6 + i * 16;
    let w = buf[off], h = buf[off + 1]; if (w === 0) w = 256; if (h === 0) h = 256;
    const bitCount = buf.readUInt16LE(off + 6);
    const size = buf.readUInt32LE(off + 8);
    const dataOffset = buf.readUInt32LE(off + 12);
    const score = w * h * 1000 + bitCount;
    if (!best || score > best.score) best = { size, dataOffset, score };
  }
  if (!best) throw new Error('empty ICO directory');
  const img = buf.slice(best.dataOffset, best.dataOffset + best.size);
  if (img.length >= 8 && img.readUInt32BE(0) === 0x89504e47) return decodePNG(img);
  return decodeIcoBitmap(img);
}
function decodeFavicon(buf) {
  if (buf.length >= 8 && buf.readUInt32BE(0) === 0x89504e47) return decodePNG(buf);
  if (buf.length >= 4 && buf.readUInt16LE(0) === 0 && buf.readUInt16LE(2) === 1) return decodeIco(buf);
  throw new Error('unsupported favicon format (need PNG or ICO)');
}
// Quantize non-transparent, non-neutral pixels into coarse color buckets, weight each
// bucket by frequency * saturation (so a small vibrant logo mark outranks a big grey/white
// background), and return the top N as deduplicated hex swatches.
function extractSwatches(img, maxSwatches) {
  maxSwatches = maxSwatches || 5;
  const STEP = 32;
  const buckets = new Map();
  for (let i = 0; i < img.pixels.length; i += 4) {
    const r = img.pixels[i], g = img.pixels[i + 1], b = img.pixels[i + 2], a = img.pixels[i + 3];
    if (a < 128) continue;
    const max = Math.max(r, g, b), min = Math.min(r, g, b);
    if (max < 24 || min > 235) continue; // skip near-black / near-white
    const sat = max === 0 ? 0 : (max - min) / max;
    const key = Math.round(r / STEP) + ',' + Math.round(g / STEP) + ',' + Math.round(b / STEP);
    let bucket = buckets.get(key);
    if (!bucket) { bucket = { r: 0, g: 0, b: 0, count: 0, satSum: 0 }; buckets.set(key, bucket); }
    bucket.r += r; bucket.g += g; bucket.b += b; bucket.count++; bucket.satSum += sat;
  }
  const toHex = (v) => v.toString(16).padStart(2, '0');
  const hexDist = (h1, h2) => Math.sqrt([1, 3, 5].reduce((s, i) => {
    const d = parseInt(h1.slice(i, i + 2), 16) - parseInt(h2.slice(i, i + 2), 16); return s + d * d;
  }, 0));
  const ranked = [...buckets.values()]
    .map((c) => ({
      hex: '#' + toHex(Math.round(c.r / c.count)) + toHex(Math.round(c.g / c.count)) + toHex(Math.round(c.b / c.count)),
      weight: c.count * (0.4 + c.satSum / c.count)
    }))
    .sort((a, b) => b.weight - a.weight);
  const out = [];
  for (const c of ranked) {
    if (out.some((h) => hexDist(h, c.hex) < 40)) continue;
    out.push(c.hex);
    if (out.length >= maxSwatches) break;
  }
  return out;
}

function htmlToText(html) {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<noscript[\s\S]*?<\/noscript>/gi, ' ')
    .replace(/<!--[\s\S]*?-->/g, ' ')
    .replace(/<(br|\/p|\/div|\/li|\/tr|\/h[1-6]|\/section|\/article|\/header)[^>]*>/gi, '\n')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&#(\d+);/g, (m, d) => String.fromCharCode(+d))
    .replace(/[ \t]+/g, ' ')
    .replace(/\n\s*\n+/g, '\n')
    .trim();
}

// ---------- Schedule parsing (heuristic) ----------
// Strategy 0: structured JSON embedded in the page. Many conference sites (WBR/eTail,
// anything Vue/React server-seeded, or schema.org ld+json) ship the full agenda inline.
function decodeEntities(s) {
  return s.replace(/&quot;/g, '"').replace(/&#0?39;/g, "'").replace(/&lt;/g, '<')
          .replace(/&gt;/g, '>').replace(/&#(\d+);/g, (m, d) => String.fromCharCode(+d))
          .replace(/&amp;/g, '&');
}
function stripTags(s) { return String(s || '').replace(/<[^>]+>/g, '').trim(); }
function speakerLine(sp) {
  if (!Array.isArray(sp)) return '';
  return sp.map(x => [x.name, x.job_title, x.company].filter(Boolean).join(', ')).join(' · ').slice(0, 160);
}
function parseStructured(html) {
  // 0a: WBR/Vue ":days" prop — HTML-escaped JSON array of {name, groups[{tracks[{sessions[...]}]}]}
  let m = html.match(/:days\s*=\s*"(\[[\s\S]*?)"\s*[:>a-z-]/i);
  if (m) {
    try {
      const days = JSON.parse(decodeEntities(m[1]));
      const out = [];
      for (const d of days) {
        const dayShort = stripTags(d.date_shortest || d.name || '');
        for (const g of d.groups || []) for (const t of g.tracks || []) for (const s of t.sessions || []) {
          const time = (dayShort ? dayShort + ' ' : '') + (s.start || '') + (s.end ? '–' + s.end : '');
          out.push({
            id: out.length,
            time: time.trim().slice(0, 40),
            title: stripTags(s.name).slice(0, 120),
            speaker: speakerLine(s.speakers),
            desc: stripTags(s.description).slice(0, 500),
            day: stripTags(d.name || '')
          });
        }
      }
      if (out.length) return out;
    } catch (e) { /* fall through */ }
  }
  // 0b: schema.org ld+json Event/EventSchedule blocks
  const ld = [...html.matchAll(/<script[^>]*application\/ld\+json[^>]*>([\s\S]*?)<\/script>/gi)];
  for (const b of ld) {
    try {
      let j = JSON.parse(b[1].trim());
      const items = Array.isArray(j) ? j : (j['@graph'] || [j]);
      const evs = items.filter(x => /Event/i.test(String(x['@type'])) && x.name && x.startDate);
      if (evs.length >= 3) {
        return evs.slice(0, 200).map((e, i) => ({
          id: i,
          time: String(e.startDate).replace('T', ' ').slice(0, 16),
          title: stripTags(e.name).slice(0, 120),
          speaker: stripTags((e.performer && (e.performer.name || (e.performer[0] || {}).name)) || '').slice(0, 80),
          desc: stripTags(e.description || '').slice(0, 500)
        }));
      }
    } catch (e) { /* fall through */ }
  }
  return null;
}
// Guess a short event/conference name from the agenda page, to suggest as the R1/phone
// header label. Prefers og:site_name (usually just the event brand, e.g. "SaaStr"), then
// og:title, then <title> with common boilerplate suffixes trimmed off.
function guessEventName(html) {
  const metaMatch = (prop) => {
    const re = new RegExp('<meta[^>]+(?:property|name)=["\']' + prop + '["\'][^>]+content=["\']([^"\']+)["\']', 'i');
    const m = html.match(re);
    return m ? decodeEntities(m[1]).trim() : '';
  };
  let name = metaMatch('og:site_name');
  if (!name) name = metaMatch('og:title');
  if (!name) {
    const t = html.match(/<title[^>]*>([^<]+)<\/title>/i);
    if (t) name = decodeEntities(t[1]).trim();
  }
  if (!name) return '';
  name = name.replace(/\s*[|\-–—:]\s*(agenda|schedule|home|homepage)\b.*$/i, '')
    .replace(/\b(agenda|schedule)\b/gi, '').replace(/\s{2,}/g, ' ').trim();
  return name.slice(0, 40);
}

// Looks for lines with time patterns; the following title-ish text becomes the session.
const TIME_RE = /\b(\d{1,2}:\d{2}\s*(?:AM|PM|am|pm)?(?:\s*[-–—to]+\s*\d{1,2}:\d{2}\s*(?:AM|PM|am|pm)?)?)\b/;
function parseSchedule(text) {
  const lines = text.split('\n').map(l => l.trim()).filter(l => l.length > 0);
  const sessions = [];
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(TIME_RE);
    if (!m) continue;
    const time = m[1].replace(/\s+/g, '');
    // title: rest of this line after the time, else the next non-time line
    let title = lines[i].replace(TIME_RE, '').replace(/^[\s\-–—:|•]+|[\s\-–—:|•]+$/g, '');
    let speaker = '';
    let j = i + 1;
    if (title.length < 4 && j < lines.length && !TIME_RE.test(lines[j])) { title = lines[j]; j++; }
    // speaker: next short line that looks like a name/company (has letters, < 80 chars, not a time)
    if (j < lines.length && !TIME_RE.test(lines[j]) && lines[j].length < 80 && /[A-Za-z]/.test(lines[j])) speaker = lines[j];
    title = title.slice(0, 120);
    if (title.length >= 4) sessions.push({ id: sessions.length, time, title, speaker: speaker.slice(0, 80) });
    if (sessions.length >= 60) break;
  }
  return sessions;
}

// ---------- HTTP plumbing ----------
function send(res, code, body, type) {
  const buf = typeof body === 'string' || Buffer.isBuffer(body) ? body : JSON.stringify(body);
  res.writeHead(code, {
    'Content-Type': type || 'application/json; charset=utf-8',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET,POST,DELETE,OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Cache-Control': 'no-store'
  });
  res.end(buf);
}
function readBody(req) {
  return new Promise((resolve, reject) => {
    let d = '';
    req.on('data', c => { d += c; if (d.length > 1e6) { req.destroy(); reject(new Error('body too large')); } });
    req.on('end', () => { try { resolve(d ? JSON.parse(d) : {}); } catch (e) { reject(e); } });
    req.on('error', reject);
  });
}
const MIME = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript', '.css': 'text/css', '.png': 'image/png', '.json': 'application/json' };

const server = http.createServer(async (req, res) => {
  const u = new URL(req.url, 'http://x');
  const p = u.pathname;
  if (req.method === 'OPTIONS') return send(res, 204, '');
  try {
    // ---- API ---- (device id via ?d= query or body.d)
    const qd = u.searchParams.get('d');
    if (p === '/healthz') return send(res, 200, { ok: true, up: process.uptime() | 0 });
    if (p === '/api/config' && req.method === 'GET') return send(res, 200, loadConfig(qd));
    if (p === '/api/config' && req.method === 'POST') {
      const body = await readBody(req);
      const id = body.d || qd;
      delete body.d;
      const prev = loadConfig(id);
      // Merge favorites from phone + R1 rather than overwriting (cross-device favs).
      if (body.favs && prev.favs) body.favs = Object.assign({}, prev.favs, body.favs);
      // Merge per-session intel by id too — the R1 pushes one session's result at a time
      // (it does the LLM analysis; the phone just mirrors whatever's landed so far).
      if (body.intel && prev.intel) body.intel = Object.assign({}, prev.intel, body.intel);
      const cfg = { ...prev, ...body };
      cfg.rev = (cfg.rev || 0) + 1;
      saveConfig(id, cfg);
      return send(res, 200, { ok: true, rev: cfg.rev });
    }
    // "Start fresh": wipe this device's config entirely. loadConfig() falls back to the
    // pristine default (rev 0) once the file's gone, so the R1's 20s poll picks up the reset
    // on its own (rev goes from whatever it was down to 0, which is still "changed").
    if (p === '/api/config' && req.method === 'DELETE') {
      const id = qd;
      if (!id) return send(res, 400, { error: 'device id required' });
      const fp = devPath(id);
      if (fs.existsSync(fp)) fs.unlinkSync(fp);
      return send(res, 200, { ok: true });
    }
    if (p === '/api/schedule' && req.method === 'POST') {
      const { url, d } = await readBody(req);
      const id = d || qd;
      if (!url) return send(res, 400, { error: 'url required' });
      const html = await fetchHtml(url);
      const structured = parseStructured(html);
      const sessions = structured || parseSchedule(htmlToText(html));
      const cfg = loadConfig(id);
      cfg.scheduleUrl = url;
      if (sessions.length) cfg.sessions = sessions;
      cfg.rev = (cfg.rev || 0) + 1;
      saveConfig(id, cfg);
      return send(res, 200, { sessions, source: structured ? 'structured' : 'heuristic', eventName: guessEventName(html), rawText: sessions.length ? undefined : htmlToText(html).slice(0, 6000) });
    }
    if (p === '/api/extract' && req.method === 'POST') {
      const { url, save, d } = await readBody(req);
      const id = d || qd;
      if (!url) return send(res, 400, { error: 'url required' });
      const text = htmlToText(await fetchHtml(url)).slice(0, 5000);
      if (save === 'company') {
        const cfg = loadConfig(id);
        cfg.companyUrl = url;
        cfg.companySummary = text.slice(0, 2500);
        saveConfig(id, cfg);
      }
      return send(res, 200, { text });
    }
    // Prospect intel context: bundle my-company summary + prospect scrape for the R1 LLM
    if (p === '/api/intel' && req.method === 'POST') {
      const { prospect, prospectUrl, d } = await readBody(req);
      const cfg = loadConfig(d || qd);
      let prospectText = '';
      if (prospectUrl) { try { prospectText = htmlToText(await fetchHtml(prospectUrl)).slice(0, 2500); } catch (e) { prospectText = ''; } }
      return send(res, 200, {
        myCompany: cfg.companySummary || '',
        prospect: prospect || '',
        prospectText
      });
    }
    // Suggest accent-color swatches by pulling the company site's favicon and pixel-mathing
    // its dominant non-neutral colors. Best-effort: unsupported image formats (SVG/JPEG/GIF)
    // or a missing favicon just come back with an empty swatch list, not an error.
    if (p === '/api/brandcolors' && req.method === 'POST') {
      const { url } = await readBody(req);
      if (!url) return send(res, 400, { error: 'url required' });
      let faviconUrl = null;
      try { faviconUrl = await getFaviconUrl(url); } catch (e) { return send(res, 200, { swatches: [], faviconUrl: null }); }
      try {
        const { buffer } = await fetchBytes(faviconUrl, 8000);
        const img = decodeFavicon(buffer);
        return send(res, 200, { swatches: extractSwatches(img, 5), faviconUrl });
      } catch (e) {
        return send(res, 200, { swatches: [], faviconUrl, note: String(e.message || e) });
      }
    }
    // ---- Static ----
    if (p === '/manifest.json') {
      const bcfg = loadConfig(qd);
      const brandName = (bcfg.brandName || '').slice(0, 40);
      return send(res, 200, JSON.stringify({
        name: brandName ? brandName + ' — Conf Companion' : 'Conf Companion',
        short_name: brandName ? brandName.slice(0, 12) : 'ConfComp',
        start_url: '/phone' + (qd ? '?d=' + qd : ''),
        display: 'standalone', background_color: '#111111', theme_color: bcfg.brandColor || '#5e6ad2',
        icons: [{ src: '/icon-192.png', sizes: '192x192', type: 'image/png' }]
      }), 'application/manifest+json');
    }
    let fp = null;
    if (p === '/' || p === '/phone' || p === '/phone/') fp = path.join(ROOT, 'phone.html');
    else if (p === '/setup') fp = path.join(ROOT, 'setup.html');
    else if (p === '/icon-192.png') fp = path.join(ROOT, 'icon-192.png');
    else if (p === '/r1' || p === '/r1/') fp = path.join(ROOT, 'r1', 'index.html');
    else if (p.startsWith('/r1/')) fp = path.join(ROOT, 'r1', p.slice(4).replace(/\.\./g, ''));
    if (fp && fs.existsSync(fp)) return send(res, 200, fs.readFileSync(fp), MIME[path.extname(fp)] || 'application/octet-stream');
    return send(res, 404, { error: 'not found' });
  } catch (e) {
    return send(res, 500, { error: String(e.message || e) });
  }
});
server.listen(PORT, () => console.log('ConfCompanion on http://localhost:' + PORT));
